services:
  web: 
    build:
      context: app
      target: builder
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app:rw
      - ./app/data:/app/data:rw
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://${SQL_USER}:${SQL_PASSWORD}@db/${SQL_DATABASE}
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:13.5-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:7.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: